### ISSUE TITLE
o_falcon2_11b_q4_1 blank responce and stuck on first question in chat ai. 

### ISSUE THREAD

**Issue by Willburn** [dcSpark/shinkai-node#437]
Asking two questios Falcon repsonce is blank and desk notification is always for first question. Then using Lama I get a correct responce.
![image](https://github.com/dcSpark/shinkai-node/assets/7295996/4252f251-d9aa-4aed-a966-1c67ba9e5b22)

**Comment by nicarq** [comment]
thank for filling the issue
<img width="1384" alt="Screenshot 2024-06-12 at 11 00 20 AM" src="https://github.com/dcSpark/shinkai-node/assets/1622112/01b5ea20-368a-4888-90c7-b323418f8360">
! it's fixed in the latest node version, we changed how the prompt system work. we are sending a new release very soon.

**Comment by nicarq** [comment]
it should be fixed. thanks for creating the issue!
